agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView
app_name = 'agents'
urlpatterns = [
    path('',AgentListView.as_view(), name='agent_list'),
    path('create/',AgentCreateView.as_view(), name='agent_create'),
]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from leads.views import  LandingView, SignUpView
from django.contrib.auth.views import LoginView, LogoutView




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingView.as_view(), name='landing_page'),
    path('leads/', include('leads.urls', namespace='lead',)),
    path('agents/', include('agents.urls', namespace='agents',)),
    path('register/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login' ),
    path('logout/', LogoutView.as_view(), name='logout' )
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    

leads/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='lead_list'),
    path('create/', views.LeadCreateView.as_view(), name='lead_create'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead_detail',),
    path('<int:pk>/update/', views.LeadUpdateView.as_view(), name='lead_update'),
    path('<int:pk>/delete/', views.lead_delete, name='lead_delete',),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save

# Create your models here.
class User(AbstractUser):
    pass

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username

class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    location = models.CharField(max_length=800, blank=True)
    phone_number = models.IntegerField( default='+234')
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

def post_user_create_signal(sender, instance, created, **kwargs):
    print(instance, created, sender)
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_create_signal, sender=User)

agents/forms.py
from django.forms import Form, ModelForm

from leads.models import Agent

class AgentModelForm(ModelForm):
    class Meta:
        model = Agent
        fields = (
            'user',
        )

leads/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model



User = get_user_model()

class SignUpForm(UserCreationForm):
    class Meta:
        model = User    
        fields = ['first_name', 'last_name', 'username', 'password1', 'password2',]

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = models.Lead
        fields = (
            "first_name",
            "last_name",
            "age",
            "agent",
        )


class LeadForm(forms.Form):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    age = forms.IntegerField(min_value=0)

agents/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from leads.models import Agent
from . forms import AgentModelForm
# Create your views here.

class AgentListView(LoginRequiredMixin,generic.ListView):
    template_name = 'agents/agent_list.html'
    context_object_name = 'agents'
    """
    def get_queryset(self):
        return Agent.objects.all()
    """
    model = Agent
    queryset = Agent.objects.all()
    

class AgentCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'agents/agent_create.html'
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agents:agent_list')

    def form_valid(self, form):
        print(self)
        agent = form.save(commit=False)
        agent.organisation = self.request.user.userprofile
        agent.save()
        return super(AgentCreateView, self).form_valid(form)

leads/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse
from . models import Agent, Lead
from . import forms
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class SignUpView(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = forms.SignUpForm
    
    def get_success_url(self):
        return reverse('login')


class LandingView(generic.TemplateView):
    template_name = "landing.html"

def landing_page_view( request,*args, **kwargs):
    return render(request,'landing.html' ,*args, **kwargs,)
########################################

class LeadListView(LoginRequiredMixin,generic.ListView):
    template_name       = 'leads/lead_list.html'
    context_object_name = 'leads'
    queryset            = Lead.objects.all()


def lead_list(request):
    leads = Lead.objects.all()
    context = {
        'leads':leads
    }
    return render(request, 'leads/lead_list.html', context)

#######################################

class LeadDetailView(LoginRequiredMixin,generic.DetailView):
    template_name       = 'leads/lead_detail.html'
    context_object_name = 'lead'
    queryset            = Lead.objects.all()


def lead_details(request,pk):
    lead_detail = Lead.objects.get(id = pk)
    context ={
        'lead':lead_detail
    }
    print(lead_detail)
    return render(request, 'leads/lead_detail.html', context)

###########################################

class LeadCreateView(LoginRequiredMixin,generic.CreateView):
    template_name   = 'leads/lead_create.html'
    form_class      = forms.LeadModelForm
    
    def get_success_url(self): #if form is save
        return reverse("leads:lead_list")

    def form_valid(self, form):
        """
        send_mail(
            subject='A leed has been created',
            message='Go to the side to see your lead',
            from_email='mondaysolomon01@gmail.com',
            recipient_list=['','mondaysolomon02@gmail.com','monday_solomon@yahoo.com']
        )
        """
        return super(LeadCreateView, self).form_valid(form)


def lead_create(request):
    form = forms.LeadModelForm()
    if request.method == "POST":
        form = forms.LeadModelForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('leads:lead_list')
    context = {
        'form':form    
    }
    return render(request, 'leads/lead_create.html', context)

#since modeform is used, form.save() will do the work of line 30 downwards
##############################################
class LeadUpdateView(LoginRequiredMixin,generic.UpdateView):
    template_name   = 'leads/lead_update.html'
    form_class      = forms.LeadModelForm
    queryset        = Lead.objects.all()
    def get_success_url(self): #if form is save
        return redirect("leads:lead_list")



def lead_update(request,pk):
    lead_detail     =   Lead.objects.get(id = pk)
    form            =   forms.LeadModelForm(instance=lead_detail)
    if request.method == "POST":
        form = forms.LeadModelForm(request.POST, instance=lead_detail)

        if form.is_valid():
            form.save()
            return redirect('leads:lead_list')

    context ={
        'lead':lead_detail,
        'form': form,
    }
    print(lead_detail)
    return render(request, 'leads/lead_update.html', context)

################################################

class LeadDeleteView(LoginRequiredMixin,generic.DeleteView):
    template_name   =     'leads/lead_delete.html' #requires me creating a template, but i will stick with FBV
    form_class      =      forms.LeadModelForm
    queryset        =      Lead.objects.all()
    def get_success_url(self): #if form is save
        return redirect("leads:lead_list")



def lead_delete(request, pk):
    lead = Lead.objects.get(id = pk)
    lead.delete()
    return redirect('/leads')

agents/templates/agents/agent_create.html
{% extends 'base.html' %}

{% block content %}

    <a href="{% url 'agents:agent_list' %}">Back to list of Agents</a>
    <hr>
    <h1>
        Create New Agent
    </h1>
        
    <div>
        <form action="" method="post">  
            {% csrf_token %}
            {{form.as_p}}

            <input type="submit" value="Submit">

        </form>
    </div>

{% endblock content %}

agents/templates/agents/agent_list.html
{% extends 'base.html' %}   

{% block content %}

<section class="text-gray-400 bg-gray-900 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">

        <div class=" w-full mb-6 py-6  flex justify-between items-center border-b border-gray-200" >
                <div>
                    <h1 class="text-4xl text-white-800">
                       Agents
                    </h1>
                </div>
                <div>
                    <a class="text-white-500 hover:text-blue-500" href="{% url 'agents:agent_create' %}">Create new Agents</a>
                </div>
        </div>
            <br>
    <div class="flex flex-wrap -m-4">
    {% for agent in agents %}
    
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-800 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-gray-800 text-indigo-400 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-white text-lg title-font font-medium mb-3">{{ agent.user.username }}</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            
            <a {% comment "yh" %} href="{% url 'agents:agent_detail' agent.pk %}"{% endcomment %} class="mt-3 text-indigo-400 inline-flex items-center">View this lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      
    {% endfor %}
    </div>
  </div>
</section>  

{% endblock content %}

leads/templates/leads/lead_create.html
{% extends 'base.html' %}

{% block content %}

    <a href="{% url 'leads:lead_list' %}">Back to list of leads</a>
    <hr>
    <h1>
        Create New Lead
    </h1>
        
    <div>
        <form action="" method="post">  
            {% csrf_token %}
            {{form.as_p}}

            <input type="submit" value="Submit">

        </form>
    </div>

{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends 'base.html' %}
{% block content %}


<section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-white text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead_detail' lead.pk  %}"
            class="flex-grow text-indigo-400 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
          <a class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Reviews</a>
          <a href="{% url 'leads:lead_update' lead.pk  %}"
            class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Update Details</a>
        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy
          chia microdosing tilde DIY. XOXO fam iligo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1
          seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-white">{{lead.age}}</span>
        </div>
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-white">{{lead.location}}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-800 py-2">
          <span class="text-gray-500">Telephone</span>
          <span class="ml-auto text-white">{{lead.phone_number}}</span>
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-white">$58.00</span>
          <a href="{% url 'leads:lead_delete' lead.pk  %}"
            class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete
            lead</a>
          <button
            class="rounded-full w-10 h-10 bg-gray-800 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5"
              viewBox="0 0 24 24">
              <path
                d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z">
              </path>
            </svg>
          </button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends 'base.html' %}   

{% block content %}

<section class="text-gray-400 bg-gray-900 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">

        <div class=" w-full mb-6 py-6  flex justify-between items-center border-b border-gray-200" >
                <div>
                    <h1 class="text-4xl text-white-800">
                        Leads
                    </h1>
                </div>
                <div>
                    <a class="text-white-500 hover:text-blue-500" href="{% url 'leads:lead_create' %}">Create new leads</a>
                </div>
        </div>
            <br>
    <div class="flex flex-wrap -m-4">
    {% for lead in leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-800 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-gray-800 text-indigo-400 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-white text-lg title-font font-medium mb-3">{{lead.first_name}} {{lead.last_name}}</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a href="{% url 'leads:lead_detail' lead.pk %}" class="mt-3 text-indigo-400 inline-flex items-center">View this lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</section>  

{% endblock content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}

{% block content %}


<section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-white text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead_detail' lead.pk  %}" class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Overview</a>
          <a   class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Reviews</a>
          <a href="{% url 'leads:lead_update' lead.pk  %}" class="flex-grow text-indigo-400 border-b-2 border-indigo-500 py-2 text-lg px-1">Update Details</a>
        </div>
       <form action="" method="post">  
            {% csrf_token %}
            {{form.as_p}}

            <input type="submit" value="Submit">
        </form>
        <a href="{% url 'leads:lead_delete' lead.pk  %}" class="flex w-24 ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete lead</a>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>



{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vue-CRM</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
    


</body>
</html>

templates/landing.html
{% extends 'base.html' %}
{% block content %}
<section class="text-gray-400 bg-gray-900 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">CRM built with django and tailwind-css</h1>
      <p class="leading-relaxed mb-8">tousled. We Help Manage your Leads.</p>
      <div class="flex justify-center">
        <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
        <button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Button</button>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-400 bg-gray-900 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Vue-CRM</span>
    </a>
    
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a href='{% url 'leads:lead_list' %}' class="mr-5 hover:text-white">Leads</a>
    {% if not request.user.is_authenticated %}
      <a href="{% url 'signup' %}" class="mr-5 hover:text-white">Sign-Up</a>
    {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
    <span>
      Welcome {{request.user.username}} 
    </span>
    <a href="{% url 'logout' %}"  class="ml-3 inline-flex items-center bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-gray-700 rounded text-base mt-4 md:mt-0">
        Logout
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% else %}
    <a href="{% url 'login' %}"  class="inline-flex items-center bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-gray-700 rounded text-base mt-4 md:mt-0">
        Login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>